### ISSUE TITLE
Assert visible selected view with text not working if descendant of matching view also has matching text

### ISSUE THREAD

**Issue by winghouchan** [mobile-dev-inc/Maestro#2651]
### Is there an existing issue for this?

- [x] I have searched the existing issues and didn't find mine.

### Steps to reproduce

> [!NOTE]
>
> A minimal, reproducible example is still work-in-progress. See **anything else** section for more details.

#### Environment

- iOS 17.x Simulator
- iOS 18.x Simulator

#### Test flow

```yaml
- launchApp

- tapOn:
    text: Text

- assertVisible:
    text: Text
    selected: true
```

#### View hierarchy

```json
// ...

{
  "attributes": {
    "accessibilityText": "Text",
    "bounds": "[101,103][262,140]",
    "enabled": "true",
    "focused": "false",
    "selected": "true",
    "checked": "false"
  },
  "children": [
    {
      "attributes": {
        "accessibilityText": "Text",
        "bounds": "[127,113][236,130]",
        "enabled": "true",
        "focused": "false",
        "selected": "false",
        "checked": "false"
      },
      "children": [
        {
          "attributes": {
            "accessibilityText": "Text",
            "bounds": "[127,113][236,130]",
            "enabled": "true",
            "focused": "false",
            "selected": "false",
            "checked": "false"
          },
          "enabled": true,
          "focused": false,
          "checked": false,
          "selected": false
        }
      ],
      "enabled": true,
      "focused": false,
      "checked": false,
      "selected": false
    }
  ],
  "enabled": true,
  "focused": false,
  "checked": false,
  "selected": true
}

// ...
```

### Actual results

```yaml
- assertVisible:
    text: Text
    selected: true
```

The selector **does not** have a match.

### Expected results

```yaml
- assertVisible:
    text: Text
    selected: true
```

The selector has a match.

### About app

- React Native `0.79.5`
- Expo `53.0.19`

### About environment

Development machine:
 
- OS: macOS 15.5
- Processor: Apple M1, arm64
- Java: 17.0.2
- Xcode: 16.4

CI machine:

- OS:  macOS 14.7.6
- Processor: Apple M1, arm64
- Java: 17
- Xcode: 15.0.1

### Logs

<details>
<summary>Logs</summary>

```
00:00:00.376 [ INFO] maestro.cli.runner.MaestroCommandRunner.invoke: Tap on "${text}" COMPLETED
00:00:00.377 [ INFO] maestro.cli.runner.MaestroCommandRunner.invoke: Assert that "${text}" is visible RUNNING
00:00:00.385 [ INFO] maestro.cli.runner.MaestroCommandRunner.invoke: Assert that "${text}" is visible metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(assertConditionCommand=AssertConditionCommand(condition=Condition(platform=null, visible=ElementSelector(textRegex=Text, idRegex=null, size=null, below=null, above=null, leftOf=null, rightOf=null, containsChild=null, containsDescendants=null, traits=null, index=null, enabled=null, optional=false, selected=true, checked=null, focused=null, childOf=null, css=null), notVisible=null, scriptCondition=null, label=null), timeout=null, label=null, optional=false)), logMessages=[], insight=Insight(message=, level=NONE), aiReasoning=null, labeledCommand=null)
00:00:00.394 [ INFO] ios.xctest.XCTestIOSDevice.invoke: Device info DeviceInfo(widthPixels=1179, heightPixels=2556, widthPoints=393, heightPoints=852)
00:00:00.394 [ INFO] device.IOSDevice.viewHierarchy: Requesting view hierarchy of the screen
00:00:00.519 [TRACE] ios.xctest.XCTestIOSDevice.invoke: Depth received: 35
00:00:00.519 [ INFO] device.IOSDevice.viewHierarchy: Depth of the screen is 35

// Repeated 122 times

00:00:16.589 [ INFO] maestro.cli.runner.MaestroCommandRunner.invoke: Assert that "${text}" is visible metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(assertConditionCommand=AssertConditionCommand(condition=Condition(platform=null, visible=ElementSelector(textRegex=Text, idRegex=null, size=null, below=null, above=null, leftOf=null, rightOf=null, containsChild=null, containsDescendants=null, traits=null, index=null, enabled=null, optional=false, selected=true, checked=null, focused=null, childOf=null, css=null), notVisible=null, scriptCondition=null, label=null), timeout=null, label=null, optional=false)), logMessages=[], insight=Insight(message=, level=NONE), aiReasoning=null, labeledCommand=null)
00:00:16.596 [ INFO] ios.xctest.XCTestIOSDevice.invoke: Device info DeviceInfo(widthPixels=1179, heightPixels=2556, widthPoints=393, heightPoints=852)
00:00:16.596 [ INFO] device.IOSDevice.viewHierarchy: Requesting view hierarchy of the screen
00:00:16.714 [TRACE] ios.xctest.XCTestIOSDevice.invoke: Depth received: 35
00:00:16.715 [ INFO] device.IOSDevice.viewHierarchy: Depth of the screen is 35
00:00:16.715 [ INFO] maestro.cli.runner.MaestroCommandRunner.invoke: Assert that "${text}" is visible metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(assertConditionCommand=AssertConditionCommand(condition=Condition(platform=null, visible=ElementSelector(textRegex=Text, idRegex=null, size=null, below=null, above=null, leftOf=null, rightOf=null, containsChild=null, containsDescendants=null, traits=null, index=null, enabled=null, optional=false, selected=true, checked=null, focused=null, childOf=null, css=null), notVisible=null, scriptCondition=null, label=null), timeout=null, label=null, optional=false)), logMessages=[], insight=Insight(message=, level=NONE), aiReasoning=null, labeledCommand=null)
00:00:16.716 [ERROR] maestro.orchestra.Orchestra.executeCommands: [Command execution] CommandFailed: Assertion is false: "Text" is visible
00:00:16.719 [ INFO] maestro.Maestro.takeScreenshot: Taking screenshot
00:00:16.720 [TRACE] maestro.utils.ScreenshotUtils.takeScreenshot: Taking screenshot to output sink
00:00:16.787 [ INFO] maestro.cli.runner.MaestroCommandRunner.invoke: Assert that "${text}" is visible FAILED
```

</details>

### Maestro version

1.39.13, 1.41.0

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

The actual problem has been very intermittent – difficult to reproduce on a local machine but frequent enough on CI to be annoying. I have been able to identify the difference in the view hierarchy of passing and failing cases. In **passing** cases, the deepest child with `accessibilityText: "Text"` does not exist:

```diff
diff --git a/fail.json b/pass.json
index 5a89002..f1eade3 100644
--- a/fail.json
+++ b/pass.json
@@ -1,46 +1,31 @@
 {
   "attributes": {
     "accessibilityText": "Text",
     "bounds": "[101,103][262,140]",
     "enabled": "true",
     "focused": "false",
     "selected": "true",
     "checked": "false"
   },
   "children": [
     {
       "attributes": {
         "accessibilityText": "Text",
         "bounds": "[127,113][236,130]",
         "enabled": "true",
         "focused": "false",
         "selected": "false",
         "checked": "false"
       },
-      "children": [
-        {
-          "attributes": {
-            "accessibilityText": "Text",
-            "bounds": "[127,113][236,130]",
-            "enabled": "true",
-            "focused": "false",
-            "selected": "false",
-            "checked": "false"
-          },
-          "enabled": true,
-          "focused": false,
-          "checked": false,
-          "selected": false
-        }
-      ],
+      "children": [],
       "enabled": true,
       "focused": false,
       "checked": false,
       "selected": false
     }
   ],
   "enabled": true,
   "focused": false,
   "checked": false,
   "selected": true
 }
```

```diff
diff --git a/fail.log b/pass.log
index 1c01282..e84c009 100644
--- a/fail.log
+++ b/pass.log
@@ -1,5 +1,5 @@
 [ INFO] maestro.cli.runner.MaestroCommandRunner.invoke: Assert that "${text}" is visible metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(assertConditionCommand=AssertConditionCommand(condition=Condition(platform=null, visible=ElementSelector(textRegex=Text, idRegex=null, size=null, below=null, above=null, leftOf=null, rightOf=null, containsChild=null, containsDescendants=null, traits=null, index=null, enabled=null, optional=false, selected=true, checked=null, focused=null, childOf=null, css=null), notVisible=null, scriptCondition=null, label=null), timeout=null, label=null, optional=false)), logMessages=[], insight=Insight(message=, level=NONE), aiReasoning=null, labeledCommand=null)
 [ INFO] ios.xctest.XCTestIOSDevice.invoke: Device info DeviceInfo(widthPixels=1179, heightPixels=2556, widthPoints=393, heightPoints=852)
 [ INFO] device.IOSDevice.viewHierarchy: Requesting view hierarchy of the screen
-[TRACE] ios.xctest.XCTestIOSDevice.invoke: Depth received: 35
-[ INFO] device.IOSDevice.viewHierarchy: Depth of the screen is 35
+[TRACE] ios.xctest.XCTestIOSDevice.invoke: Depth received: 34
+[ INFO] device.IOSDevice.viewHierarchy: Depth of the screen is 34

```

I don't yet know why the deepest child view sometimes exists and sometimes does not. I suspect it's an issue with one of my dependencies (that's the only significant difference I can tell between the WIP MCVE and the actual app). However, this is separate from the issue with Maestro – I'd still expect Maestro to successfully find a match with the view hierarchy of the currently failing case.

**Comment by Fishbowler** [comment]
Fixed by #2711

**Comment by winghouchan** [comment]
@Fishbowler: thanks to you and the team for fixing this. Will version 1.x be patched or will the fix only be released in version 2.x?

**Comment by Fishbowler** [comment]
There won't be any patches to the v1 branch.
We're expecting a v2 release later today.

Is there a reason you're stuck on v1?

**Comment by winghouchan** [comment]
Ah ok 😞 

Primary reason for not upgrading is I haven't had time to resolve breaking changes introduced by v2 (50+ tests are affected) 😅

Also #2610 is still reproducible in v2. I'm working around that issue by using 1.39.x. (Which actually means patching v1 will not resolve it for me, unless 1.39.x is patched, because I can't use 1.40.x or 1.41.x)
