### ISSUE TITLE
[1.24.0] iOS flow crashes: Failed to reach out XCUITest Server

### ISSUE THREAD

**Issue by wingcommander2020** [mobile-dev-inc/maestro#880]
Maestro: 1.24.0
XCODE: Version 14.2 (14C18)
OS: macOS 13.2.1 (22D68)

When I try to run my iOS flow, maestro crashes and I get the following error message:

```
xcuitest.XCTestDriverClient$XCTestDriverUnreachable: Failed to reach out XCUITest Server                                                                    
        at xcuitest.XCTestDriverClient$okHttpClient$2.invoke$lambda-2(XCTestDriverClient.kt:75)                                                             
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)                                                                  
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)                                                     
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)    
        at xcuitest.XCTestDriverClient.executeJsonRequest(XCTestDriverClient.kt:178)                                                                        
        at xcuitest.XCTestDriverClient.runningAppId(XCTestDriverClient.kt:125)
        at ios.xctest.XCTestIOSDevice.activeAppId(XCTestIOSDevice.kt:238)   
        at ios.xctest.XCTestIOSDevice.contentDescriptor(XCTestIOSDevice.kt:47)
        at ios.LocalIOSDevice.contentDescriptor(LocalIOSDevice.kt:32)       
        at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:179)    
	at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:29)
	at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:379)
	at maestro.Maestro$findElementWithTimeout$element$1.invoke(Maestro.kt:404)
	at maestro.Maestro$findElementWithTimeout$element$1.invoke(Maestro.kt:403)
	at maestro.utils.MaestroTimer.withTimeout(MaestroTimer.kt:16)
	at maestro.Maestro.findElementWithTimeout(Maestro.kt:403)
	at maestro.orchestra.Orchestra.findElement(Orchestra.kt:687)
	at maestro.orchestra.Orchestra.findElement$default(Orchestra.kt:669)
	at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:598)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:163)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:141)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:163)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:124)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:98)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:53)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
```

The output prior to the error message: 

```Android

[1] emulator-5554

iOS

[2] iPhone 14 - iOS 16.2 - FB6F7FDF-1A6B-43D1-AD8A-2C42CA4C7F96

Multiple running devices detected. Choose a device to run on.

Enter a number from the list above:

2
Waiting for idb service to start..
Waiting for Simulator to boot..
Waiting for successful taps
Simulator ready
```

Android flow works fine.

I guess the problem occurred after I upgraded to 1.24.0. uninstalling and reinstalling the older version using `export MAESTRO_VERSION={version}; curl -Ls "https://get.maestro.mobile.dev" | bash`
did not help either. 

Any suggestions?

**Comment by axelniklasson** [comment]
@wingcommander2020 are you seeing the same issue when running `1.23.0`?

**Comment by wingcommander2020** [comment]
My colleague is still on 1.23.0 and he does not get the error using the same flow-file. 

I already tried downgrading by manually uninstalling maestro and re-installing using 'MAESTRO_VERSION={1.23.0}'. I got version 1.23.0 but the error remained.

**Comment by axelniklasson** [comment]
Thanks for confirming @wingcommander2020 -- it does seem like something is not fully right with your local environment. Could you try recreating the simulator? If that doesn't work, can you try using another device model and/or iOS version on your sim?

**Comment by gcohen-dev** [comment]
I'm having the same problem with an older version. I've tried reinstalling all the packages and of course, updating to the latest 1.24.0 not working. 
Perhaps it's a privacy thing? since Chrome is launched but unable to start the XCUITest Server.

**Comment by wingcommander2020** [comment]
After creating a new sim device the original error message is gone. The flow fails however prematurely for any iOS simdevice I pick. This is what is visible before the flow fails:

![Screenshot 2023-03-09 at 15 09 39](https://user-images.githubusercontent.com/60811299/224051473-bfc00557-e488-4aef-9c23-04361abce60f.png)

Again on Android everything works as supposed to.

**Comment by gcohen-dev** [comment]
I'm install a new simulator and now I'm getting: 
```
java.lang.IllegalStateException: idb_companion is not able dispatch successful tap events
	at maestro.cli.device.DeviceService.startIdbCompanion(DeviceService.kt:137)
	at maestro.cli.device.DeviceService.prepareDevice(DeviceService.kt:82)
	at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:31)
	at maestro.cli.session.MaestroSessionManager.selectDevice(MaestroSessionManager.kt:113)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:63)
	at maestro.cli.command.StudioCommand.call(StudioCommand.kt:36)
	at maestro.cli.command.StudioCommand.call(StudioCommand.kt:18)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
```
Any suggestions?

**Comment by gumil** [comment]
This is also a problem in v1.23.0 and xcode version v4.1. 
````
Unable to launch app <package-name>: Failed to reach out XCUITest Server
```

**Comment by axelniklasson** [comment]
Thanks for the context folks. @berikv from our team is working on stability improvements regarding the XCUITest runner so whenever there is an update on this we'll post it here!

**Comment by berikv** [comment]
This issue is getting conflated.

1.

I'm working on a fix (https://github.com/mobile-dev-inc/maestro/pull/882) for the issue where maestro cli outputs "Failed to reach out XCUITest Server". Preferably I'd run a validation to make sure the issue is fixed. @wingcommander2020 is there a way I can run your flow? Or, alternatively, could you clone the maestro repo, checkout of the PR branch and run `./maestro ...` to test it?

2.

> The flow fails however prematurely for any iOS simdevice I pick


This is strange. @wingcommander2020, can you share more information such as log files / etc. Did you try rebooting?
Another trick that works with broken simulators is to remove (backup) the /Library/Developer/CoreSimulator/Profiles/Runtimes/* directories and reinstalling the runtimes you need through Xcode.

3. 

> This is also a problem in v1.23.0 and xcode version v4.1.

The fix I'm working on very likely also fixes this issue. @gumil is it possible for you to share a reproducible scenario or otherwise run it locally (as described above?

**Comment by jetaix** [comment]
Hi team,
I'm facing the same error in a different context:

I'm trying to run some tests on a GitHub action.

Maestro: latest -> `curl -Ls "https://get.maestro.mobile.dev" | bash`
iOS: `iPhone 14 Plus - iOS 16.2`
macOS: `macos-latest` from a [Github-hosted runners](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners)

<img width="894" alt="image" src="https://user-images.githubusercontent.com/4866709/224995706-d3597680-af1e-4c74-a75b-d1d3c840e092.png">


The same flow works locally. (with [act](https://github.com/nektos/act))

Let me know if you need more context!

**Comment by gumil** [comment]
> The fix I'm working on very likely also fixes this issue. @gumil is it possible for you to share a reproducible scenario or otherwise run it locally (as described above?

I found out that I only have this error when I use the github step action to do maestro tests. I also added an issue to the github action here https://github.com/dniHze/maestro-test-action/issues/50

**Comment by Borrowell-Roy** [comment]
I am also facing the same issue. Could this be related to machine? Using M1 here

**Comment by wingcommander2020** [comment]
> I am also facing the same issue. Could this be related to machine? Using M1 here

I am on a M2 Mac Pro, my colleague has the same hardware and no problems with an older version of Maestro <1.24.0. 
I also have a M2 Mac Air and Maestro  >=1.24.0 works fine using the same flows. I have already reset the M2 Mac Pro, but to no avail - still crashes as described above.

Could this be related to an incompatible third party library's version? @berikv Would it help to list version numbers of certain dependencies to pinpoint the problem?

**Comment by yarv-dev** [comment]
I Have the same issue on Azure Devops pipeline, which uses the github actions `macos` image.
```
Assert that "SIGN IN" is visible...xcuitest.XCTestDriverClient$XCTestDriverUnreachable: Failed to reach out XCUITest Server
	at xcuitest.XCTestDriverClient$okHttpClient$2.invoke$lambda-0(XCTestDriverClient.kt:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

```

**Comment by yanniks** [comment]
Facing the same issue on my MacBook. One possible idea: I do not have Rosetta installed on my Mac - our build server (where Maestro is running fine) does have Rosetta 2 installed.

**Comment by RafaO** [comment]
Hi, after https://github.com/mobile-dev-inc/maestro/pull/882 got merged, the problem about `Failed to reach out XCUITest Server` is not happening for me anymore. Tried with maestro version 1.26.0. 

Thanks!

**Comment by CodingItWrong** [comment]
Based on the above comment I retried on GitHub Actions, but unfortunately the problem is still occurring for me there: https://github.com/CodingItWrong/listapp-expo/actions/runs/4584588560/jobs/8358340701

**Comment by RafaO** [comment]
that's unfortunate @CodingItWrong , I took a look at your workflow file and the only difference is that I am using macos-latest, not sure if that could have an impact. Here is an example of my github actions that started working after the update, in case you want to compare by yourself: https://github.com/RafaO/yourpet/actions/runs/4709440955/jobs/8352510660

Notice as well I added an echo instruction to print the actual version of maestro that's been used so I could verify it is 1.26.

**Comment by CodingItWrong** [comment]
Thanks @RafaO; switching to `macos-latest` worked for me.

Then I tried `macos-13` because I like to lock versions down more, but my action stayed in the queue indefinitely. I would probably need to research more about what macOS versions are available, but that's not related to this issue.

**Comment by Sam-Page** [comment]
I seem to be getting the exact same problem as Yanniks too. Have tried different versions of xcode, ios and maestro, along with updating macos to no avail.

**Comment by axelniklasson** [comment]
Hi there folks, it would be much appreciated if you could try [upgrading to the most recent version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) as we have merged some fixes related to this issue and let us know if the issue still persists for you. Thanks!

**Comment by RhyG** [comment]
Also getting the error `Failed to reach out XCUITest Server` when running `1.23.0` and `1.24.0`. When upgrading to to the most recent version the app still doesn't launch, but I no longer get an error in the CLI and it fails silently. Any suggestions on how to debug that to provide some more useful error messages?

**Comment by KrisLau** [comment]
Might be related to this:
https://stackoverflow.com/questions/70298400/why-am-i-getting-an-xcuitest-failed-to-receive-any-data-within-the-timeout-5

I dont wanna downgrade node though so I guess I'll just manually write my tests 😅

**Comment by kzlukosky** [comment]
@axelniklasson I am getting the following error: 

```
com.github.michaelbull.result.UnwrapException: kotlin.Unit xcuitest.XCTestDriverClient$XCTestDriverUnreachable: Failed to reach out XCUITest Server in RetryOnError      
        at maestro.drivers.IOSDriver$deviceInfo$2.invoke(IOSDriver.kt:65)       
        at maestro.drivers.IOSDriver$deviceInfo$2.invoke(IOSDriver.kt:64)       
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)                  
        at maestro.drivers.IOSDriver.getDeviceInfo(IOSDriver.kt:64)             
        at maestro.drivers.IOSDriver.deviceInfo(IOSDriver.kt:97)                
        at maestro.Maestro.fetchDeviceInfo(Maestro.kt:57)                       
        at maestro.Maestro.access$fetchDeviceInfo(Maestro.kt:37)                
        at maestro.Maestro$cachedDeviceInfo$2.invoke(Maestro.kt:43)             
        at maestro.Maestro$cachedDeviceInfo$2.invoke(Maestro.kt:42)             
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)                  
        at maestro.Maestro.getCachedDeviceInfo(Maestro.kt:42)                   
        at maestro.Maestro.deviceInfo(Maestro.kt:51)                            
        at maestro.orchestra.Orchestra.deviceInfo(Orchestra.kt:745)             
        at maestro.orchestra.Orchestra.findElement(Orchestra.kt:732)            
        at maestro.orchestra.Orchestra.findElement$default(Orchestra.kt:717)    
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:645)           
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:172)         
        at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:520)             
	at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:429)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:201)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:150)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:93)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:163)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:124)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:99)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:57)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
```

The tests seem to start but crash part way through. Other members on my team are using the same version of Maestro and are NOT experiencing this issue so I am not sure whats going on. 

The error I am getting is very similar to the issue description so posting my experience here. 

I am using: 
- MacOS Ventura: 13.3.1
- Maestro: 1.27.0
- Java: openjdk version "20.0.1" 2023-04-18
- Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**Comment by KrisLau** [comment]
@kzlukosky It had to do with my environment for me. You might want to try reinstalling or upgrading cocoapods and rbenv (or whatever other ruby version management you might use). Also make sure no physical devices are connected. Hopefully that works for you!

**Comment by kzlukosky** [comment]
> @kzlukosky It had to do with my environment for me. You might want to try reinstalling or upgrading cocoapods and rbenv (or whatever other ruby version management you might use). Also make sure no physical devices are connected. Hopefully that works for you!

Unfortunately I did see your comment and reinstalled cocoapods and ruby already and sadly am still experiencing the same issue.

**Comment by KrisLau** [comment]
@kzlukosky Did you make sure to close all the terminal/console windows and IDE then reopen? Cause I was still getting it until I did that

**Comment by kzlukosky** [comment]
> @kzlukosky Did you make sure to close all the terminal/console windows and IDE then reopen? Cause I was still getting the errors until I did that

@KrisLau Yea I closed anything that was open, restarted by computer and tried again with the same issue. Was MacOS, Cocoapods and Ruby the only things you updated/reinstalled?

**Comment by KrisLau** [comment]
@kzlukosky Afaik, yes but I also had to do some other stuff to get my project running which might've changed things up! I did `sudo gem pristine <gem name> --version <version #>` to a bunch of different gems. Did a `pod install/update` in my ios folder. Uninstalled and reinstalled rbenv & double checked that all my environment files (.bashrc, .bash_profile, .zshrc) wwere configured with the proper script or rbenv to work. The last one is most likely to have helped if it wasn't the other stuff

**Comment by KrisLau** [comment]
no clue why but it stopped working again and my builds have this error:
```
2023-05-12 13:22:27.881 xcodebuild[16301:82268] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
2023-05-12 13:22:31.713 xcodebuild[16301:82357] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
```

**Comment by JoaoManaroulas** [comment]
> > @kzlukosky Did you make sure to close all the terminal/console windows and IDE then reopen? Cause I was still getting the errors until I did that
> 
> @KrisLau Yea I closed anything that was open, restarted by computer and tried again with the same issue. Was MacOS, Cocoapods and Ruby the only things you updated/reinstalled?

Did you manage to fix this somehow? I'm having the same issue. cc @tqirazevedo

**Comment by JoaoManaroulas** [comment]
Did anyone managed to run Maestro on an Azure Pipeline with macOS-12 or macOS-13?

I'm failling with the same error as some mentioned: Failed to reach out XCUITest Server in RetryOnError

The app seems to complete the "launch app" step but fails on the next one: asserting for visibility on a button.

It's worth mentioning that the same test case runs with no problem on my own machine which has a very similar setup:
MacOS 13.3.1
Xcode 14.2
Maestro 1.29.0

**Comment by JoaoManaroulas** [comment]
> Did anyone managed to run Maestro on an Azure Pipeline with macOS-12 or macOS-13?
> 
> I'm failling with the same error as some mentioned: Failed to reach out XCUITest Server in RetryOnError
> 
> The app seems to complete the "launch app" step but fails on the next one: asserting for visibility on a button.
> 
> It's worth mentioning that the same test case runs with no problem on my own machine which has a very similar setup: MacOS 13.3.1 Xcode 14.2 Maestro 1.29.0

Just for an update here: Doing both the installtion of the Facebook IDB Companion and Maestro within the same shell made it so that it didn't fail with 'Failed to reach out XCUITest Server in RetryOnError', which seems really weird as the app did launch on the failing scenario.

**Comment by hackdie** [comment]
if anyone having same issue on 1.30 or 1.31 seems like there is an issue on those versions. going back to 1.29 solved for us

**Comment by wingcommander2020** [comment]
My original problem was not solved, but I have not yet tried newer versions of Maestro. Most posts here are actually unrelated to my original post. Perhaps we should close this thread.
